# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

# Minecraft Properties
minecraft_version = 26.2
minecraft_version_supported = [26.1,26.2]
minecraft_version_filter = snapshots
minecraft_version_lower = 1.21.11
minecraft_version_upper = 26.3

# File Name
minecraft_version_name = 26.1(2)
archives_base_name = MoreWeaponVariants

# Mod Properties
mod_id = mstv-mweaponv
mod_name = More Weapon Variants (MStV+)
mod_name_short = More Weapon Variants
mod_description = This mod adds more variants for Swords, Bows, Crossbows and Arrows.
mod_version = 1.6.0
mod_license = CC-BY-NC-SA-4.0
maven_group = de.pnku

# Dependencies
mstv_version = 1.4.20
mstv_version_id = cizTdhQm
m_tool_v_version = 1.2.7
m_tool_v_version_id = 5JDnhL1v
not_enough_animations_version_id = 67xQnLDS
